"""0024 — inflections v2: **the tense the sentence was heard in** (parser-compiler req 9).

**A SENTENCE SPOKEN BACK IN THE WRONG TENSE IS NOT THE SAME SENTENCE.** `db/0022` built one tag,
`VBZ`, and said so in its own docstring: *«the decompiler renders the present because it does not
read the theatre yet»*. It does now — the compiler writes a theatre from the tense it hears
(req 25), and the decompiler reads it back — so the two remaining tags arrive: `VBD` for «I walked»
and `VBN` for «the mail was written», which is also the voice.

**TWO RESOURCES, NOT ONE, AND THE SECOND ONE IS PRINCETON'S.** `db/0022` found 22 of `lemminflect`'s
43 answers to be defects of its own. So this roster is cross-checked against **WordNet's
`verb.exc`** — the hand-curated list of every irregular verb form, read straight from the corpus
this project already builds its base from — and a row is written only where one of four things is
true:

    both        the two resources give the same form                       majority of the roster
    unchanging  the instrument says the past IS the lemma, and WordNet
                records only an `-ing` form for it, which is the silence
                of a verb that has nothing else to record             «hit» · «put» · «let»
    stress      the instrument's form differs from the rule by EXACTLY
                a doubled consonant — the one fact the rule declared
                out of reach, because stress is not in the spelling   «backlog» → «backlogged»
    hand        the QM ruled it, and it is listed below                 the disagreements

**THE BENCH IS `tools/inflection_bench.py`** and it is reproducible: the classification above is its
output, not a description of it. *(Written by the QM on 2026-09-20.)*

**THE RULE GREW TOO, and each change is measured rather than argued:**

    -ed / -d / -ied     the three regular spellings
    a doubled final     one-syllable CVC only — «stop» → «stopped»; the polysyllables that also
                        double do so because their last syllable is STRESSED, and those are rows
    -c  ->  -cked       «panic» → «panicked», and only after a vowel: «sync» takes a plain `-ed`
    `y` counts          as a vowel for syllables after a consonant («cypher») and as a CONSONANT
                        between vowels, which is what splits «cray|on» and «kay|ak»

**THE HAND RULINGS**, each one a case where the two resources disagreed:

    beat · browbeat · outbid · overbid · quit · rid · bet   unchanged; WordNet's form is the
                                                            PARTICIPLE («beaten»), not the past
    bestride → bestrode · crossbreed → crossbred            the instrument hyphenated or mislemmatised
    forgo → forwent · ghostwrite → ghostwrote               «forewent» and «ghost-wrote» are its defects
    overshoot → overshot · overwrite → overwrote           «over shot» and «over-wrote» likewise
    impanel → impanelled                                   it answered for «empanel», a different lemma
    output → outputted                                     WordNet's, against the rule's «outputed»
    become · come · run · overcome · outrun · rerun         the participle IS the lemma and WordNet
                                                            records only the PAST («became», «ran»)
    the zero-change verbs WordNet cannot witness            «burst» · «cast» · «cost» · «hurt» ·
                                                            «input» · «read» · «spread» · «thrust» ·
                                                            «broadcast» · «forecast» and their
                                                            compounds: WordNet lists a form only when
                                                            it DIFFERS, and these differ in nothing,
                                                            so there is no entry to agree with
    joyride → joyrode/joyridden · misdo → misdid/misdone   the instrument hyphenated or spaced them
    lipread · proofread · misread · reread                 unchanged, same family as «read»
    overeat → overate · rebind → rebound · resell → resold the instrument hyphenated them
    foreswear → foreswore/foresworn                        it answered for «forswear»

**THE MODALS ARE NOT HERE.** `can` · `will` · `shall` · `may` · `must` are closed-class rows with
their own meanings (`language_closed_classes`), not lexical verbs, and the instrument answering
«could» for `can` is answering a question nobody asked.
"""

from tk2.core.models import ALL_MODELS, BASE_MODELS, LEDGER_MODELS, InflectionDoc
from tk2.migrations import ensure_collections

VERSION = 2

TAG_PRESENT = "VBZ"
TAG_PAST = "VBD"
TAG_PARTICIPLE = "VBN"

SOURCE_PRESENT = ("lemminflect 0.2.3 over all 20,364 verb lemmas in WordNet, 2026-09-19, curated by "
                  "the QM against the spelling rule in `tk2.language.inflect`")
SOURCE = ("lemminflect 0.2.3 cross-checked against WordNet's verb.exc over 8,433 single-word verb "
          "lemmas, 2026-09-20, by `tools/inflection_bench.py`; the disagreements curated by the QM")

WHY = {
    "both": "both resources give this form",
    "unchanging": "the past is the lemma; WordNet records only an `-ing` form, which is its silence",
    "stress": "a doubled consonant the rule cannot see, because stress is not in the spelling",
    "hand": "the resources disagreed and the QM ruled it — see the docstring",
}


#: `(lemma, the form, what the rule would have said, which of the four states wrote it)`.
PAST_TENSE = (
    ('abet', 'abetted', 'abeted', 'both'),
    ('abhor', 'abhorred', 'abhored', 'both'),
    ('abut', 'abutted', 'abuted', 'both'),
    ('acquit', 'acquitted', 'acquited', 'both'),
    ('admit', 'admitted', 'admited', 'both'),
    ('allot', 'allotted', 'alloted', 'both'),
    ('annul', 'annulled', 'annuled', 'both'),
    ('apparel', 'apparelled', 'appareled', 'stress'),
    ('arise', 'arose', 'arised', 'both'),
    ('aver', 'averred', 'avered', 'both'),
    ('awake', 'awoke', 'awaked', 'both'),
    ('baa', 'baaaed', 'baaed', 'stress'),
    ('backbite', 'backbit', 'backbited', 'both'),
    ('backlog', 'backlogged', 'backloged', 'stress'),
    ('backslap', 'backslapped', 'backslaped', 'stress'),
    ('backslide', 'backslid', 'backslided', 'both'),
    ('backstop', 'backstopped', 'backstoped', 'stress'),
    ('be', 'was', 'bed', 'both'),
    ('bear', 'bore', 'beared', 'both'),
    ('beat', 'beat', 'beated', 'hand'),
    ('bebop', 'bebopped', 'beboped', 'stress'),
    ('become', 'became', 'becomed', 'both'),
    ('bedim', 'bedimmed', 'bedimed', 'both'),
    ('befall', 'befell', 'befalled', 'both'),
    ('befit', 'befitted', 'befited', 'both'),
    ('befog', 'befogged', 'befoged', 'both'),
    ('beget', 'begot', 'begeted', 'both'),
    ('begin', 'began', 'begined', 'both'),
    ('behold', 'beheld', 'beholded', 'both'),
    ('bend', 'bent', 'bended', 'both'),
    ('beseech', 'besought', 'beseeched', 'both'),
    ('beset', 'beset', 'beseted', 'unchanging'),
    ('bespeak', 'bespoke', 'bespeaked', 'both'),
    ('bestir', 'bestirred', 'bestired', 'both'),
    ('bestride', 'bestrode', 'bestrided', 'hand'),
    ('bet', 'bet', 'betted', 'hand'),
    ('bid', 'bade', 'bidded', 'both'),
    ('bind', 'bound', 'binded', 'both'),
    ('bite', 'bit', 'bited', 'both'),
    ('blackleg', 'blacklegged', 'blackleged', 'both'),
    ('bleed', 'bled', 'bleeded', 'both'),
    ('blow', 'blew', 'blowed', 'both'),
    ('bobsled', 'bobsledded', 'bobsleded', 'stress'),
    ('bootleg', 'bootlegged', 'bootleged', 'both'),
    ('bootstrap', 'bootstrapped', 'bootstraped', 'stress'),
    ('break', 'broke', 'breaked', 'both'),
    ('breed', 'bred', 'breeded', 'both'),
    ('bring', 'brought', 'bringed', 'both'),
    ('broadcast', 'broadcast', 'broadcasted', 'hand'),
    ('browbeat', 'browbeat', 'browbeated', 'hand'),
    ('buckram', 'buckrammed', 'buckramed', 'stress'),
    ('build', 'built', 'builded', 'both'),
    ('burst', 'burst', 'bursted', 'hand'),
    ('buy', 'bought', 'buyed', 'both'),
    ('carol', 'carolled', 'caroled', 'both'),
    ('cast', 'cast', 'casted', 'hand'),
    ('catch', 'caught', 'catched', 'both'),
    ('catnap', 'catnapped', 'catnaped', 'both'),
    ('cavil', 'cavilled', 'caviled', 'both'),
    ('choose', 'chose', 'choosed', 'both'),
    ('cleave', 'cleft', 'cleaved', 'both'),
    ('cling', 'clung', 'clinged', 'both'),
    ('come', 'came', 'comed', 'both'),
    ('commit', 'committed', 'commited', 'both'),
    ('compel', 'compelled', 'compeled', 'both'),
    ('concur', 'concurred', 'concured', 'both'),
    ('confab', 'confabbed', 'confabed', 'both'),
    ('confer', 'conferred', 'confered', 'both'),
    ('control', 'controlled', 'controled', 'both'),
    ('corral', 'corralled', 'corraled', 'both'),
    ('cost', 'cost', 'costed', 'hand'),
    ('counsel', 'counselled', 'counseled', 'both'),
    ('countersink', 'countersank', 'countersinked', 'both'),
    ('creep', 'crept', 'creeped', 'both'),
    ('crossbreed', 'crossbred', 'crossbreeded', 'hand'),
    ('cudgel', 'cudgelled', 'cudgeled', 'both'),
    ('cut', 'cut', 'cutted', 'unchanging'),
    ('deal', 'dealt', 'dealed', 'both'),
    ('debar', 'debarred', 'debared', 'both'),
    ('debug', 'debugged', 'debuged', 'both'),
    ('defat', 'defatted', 'defated', 'stress'),
    ('defer', 'deferred', 'defered', 'both'),
    ('defog', 'defogged', 'defoged', 'stress'),
    ('demob', 'demobbed', 'demobed', 'both'),
    ('demur', 'demurred', 'demured', 'both'),
    ('deter', 'deterred', 'detered', 'both'),
    ('devil', 'devilled', 'deviled', 'both'),
    ('dig', 'dug', 'digged', 'both'),
    ('disbar', 'disbarred', 'disbared', 'both'),
    ('disbud', 'disbudded', 'disbuded', 'both'),
    ('disembowel', 'disembowelled', 'disemboweled', 'both'),
    ('dishevel', 'dishevelled', 'disheveled', 'both'),
    ('disinter', 'disinterred', 'disintered', 'both'),
    ('dispel', 'dispelled', 'dispeled', 'both'),
    ('distil', 'distilled', 'distiled', 'both'),
    ('do', 'did', 'doed', 'both'),
    ('draw', 'drew', 'drawed', 'both'),
    ('drink', 'drank', 'drinked', 'both'),
    ('drive', 'drove', 'drived', 'both'),
    ('dwell', 'dwelt', 'dwelled', 'both'),
    ('eat', 'ate', 'eated', 'both'),
    ('eavesdrop', 'eavesdropped', 'eavesdroped', 'both'),
    ('embed', 'embedded', 'embeded', 'both'),
    ('emit', 'emitted', 'emited', 'both'),
    ('empanel', 'empanelled', 'empaneled', 'both'),
    ('enamel', 'enamelled', 'enameled', 'both'),
    ('englut', 'englutted', 'engluted', 'both'),
    ('entrap', 'entrapped', 'entraped', 'both'),
    ('enwrap', 'enwrapped', 'enwraped', 'both'),
    ('equal', 'equalled', 'equaled', 'both'),
    ('equip', 'equipped', 'equiped', 'both'),
    ('excel', 'excelled', 'exceled', 'both'),
    ('expel', 'expelled', 'expeled', 'both'),
    ('extol', 'extolled', 'extoled', 'both'),
    ('fall', 'fell', 'falled', 'both'),
    ('feed', 'fed', 'feeded', 'both'),
    ('feel', 'felt', 'feeled', 'both'),
    ('fight', 'fought', 'fighted', 'both'),
    ('find', 'found', 'finded', 'both'),
    ('flee', 'fled', 'fleed', 'both'),
    ('fling', 'flung', 'flinged', 'both'),
    ('fly', 'flew', 'flied', 'both'),
    ('forbear', 'forbore', 'forbeared', 'both'),
    ('forbid', 'forbade', 'forbided', 'both'),
    ('forecast', 'forecast', 'forecasted', 'hand'),
    ('forego', 'forewent', 'foregoed', 'both'),
    ('foresee', 'foresaw', 'foreseed', 'both'),
    ('foreswear', 'foreswore', 'foresweared', 'hand'),
    ('foretell', 'foretold', 'foretelled', 'both'),
    ('forget', 'forgot', 'forgeted', 'both'),
    ('forgive', 'forgave', 'forgived', 'both'),
    ('forgo', 'forwent', 'forgoed', 'hand'),
    ('format', 'formatted', 'formated', 'both'),
    ('forsake', 'forsook', 'forsaked', 'both'),
    ('forswear', 'forswore', 'forsweared', 'both'),
    ('freeze', 'froze', 'freezed', 'both'),
    ('ftp', 'ftpped', 'ftped', 'stress'),
    ('fulfil', 'fulfilled', 'fulfiled', 'both'),
    ('gainsay', 'gainsaid', 'gainsayed', 'both'),
    ('gambol', 'gambolled', 'gamboled', 'both'),
    ('get', 'got', 'getted', 'both'),
    ('ghostwrite', 'ghostwrote', 'ghostwrited', 'hand'),
    ('give', 'gave', 'gived', 'both'),
    ('go', 'went', 'goed', 'both'),
    ('grind', 'ground', 'grinded', 'both'),
    ('grovel', 'grovelled', 'groveled', 'both'),
    ('grow', 'grew', 'growed', 'both'),
    ('gyp', 'gypped', 'gyped', 'both'),
    ('hamstring', 'hamstrung', 'hamstringed', 'both'),
    ('handicap', 'handicapped', 'handicaped', 'both'),
    ('hang', 'hung', 'hanged', 'both'),
    ('have', 'had', 'haved', 'both'),
    ('hear', 'heard', 'heared', 'both'),
    ('hiccup', 'hiccupped', 'hiccuped', 'both'),
    ('hide', 'hid', 'hided', 'both'),
    ('hit', 'hit', 'hitted', 'unchanging'),
    ('hold', 'held', 'holded', 'both'),
    ('horsewhip', 'horsewhipped', 'horsewhiped', 'both'),
    ('hurt', 'hurt', 'hurted', 'hand'),
    ('imbed', 'imbedded', 'imbeded', 'both'),
    ('impanel', 'impanelled', 'impaneled', 'hand'),
    ('impel', 'impelled', 'impeled', 'both'),
    ('incur', 'incurred', 'incured', 'both'),
    ('infer', 'inferred', 'infered', 'both'),
    ('inlay', 'inlaid', 'inlayed', 'both'),
    ('input', 'input', 'inputed', 'hand'),
    ('inset', 'inset', 'inseted', 'unchanging'),
    ('inspan', 'inspanned', 'inspaned', 'both'),
    ('instal', 'installed', 'instaled', 'both'),
    ('instil', 'instilled', 'instiled', 'stress'),
    ('inter', 'interred', 'intered', 'both'),
    ('interbreed', 'interbred', 'interbreeded', 'both'),
    ('joyride', 'joyrode', 'joyrided', 'hand'),
    ('keep', 'kept', 'keeped', 'both'),
    ('kennel', 'kennelled', 'kenneled', 'both'),
    ('kidnap', 'kidnapped', 'kidnaped', 'both'),
    ('kneel', 'knelt', 'kneeled', 'both'),
    ('know', 'knew', 'knowed', 'both'),
    ('lay', 'laid', 'layed', 'both'),
    ('lead', 'led', 'leaded', 'both'),
    ('leap', 'leapt', 'leaped', 'both'),
    ('leapfrog', 'leapfrogged', 'leapfroged', 'both'),
    ('leave', 'left', 'leaved', 'both'),
    ('lend', 'lent', 'lended', 'both'),
    ('let', 'let', 'letted', 'unchanging'),
    ('libel', 'libelled', 'libeled', 'both'),
    ('lie', 'lay', 'lied', 'both'),
    ('light', 'lit', 'lighted', 'both'),
    ('lipread', 'lipread', 'lipreaded', 'hand'),
    ('lose', 'lost', 'losed', 'both'),
    ('make', 'made', 'maked', 'both'),
    ('manumit', 'manumitted', 'manumited', 'both'),
    ('marshal', 'marshalled', 'marshaled', 'both'),
    ('marvel', 'marvelled', 'marveled', 'both'),
    ('mean', 'meant', 'meaned', 'both'),
    ('meet', 'met', 'meeted', 'both'),
    ('miscast', 'miscast', 'miscasted', 'hand'),
    ('misdeal', 'misdealt', 'misdealed', 'both'),
    ('misdo', 'misdid', 'misdoed', 'hand'),
    ('mislay', 'mislaid', 'mislayed', 'both'),
    ('mislead', 'misled', 'misleaded', 'both'),
    ('misread', 'misread', 'misreaded', 'hand'),
    ('misspend', 'misspent', 'misspended', 'both'),
    ('mistake', 'mistook', 'mistaked', 'both'),
    ('misunderstand', 'misunderstood', 'misunderstanded', 'both'),
    ('nonplus', 'nonplussed', 'nonplused', 'both'),
    ('occur', 'occurred', 'occured', 'both'),
    ('offset', 'offset', 'offseted', 'unchanging'),
    ('omit', 'omitted', 'omited', 'both'),
    ('outbid', 'outbid', 'outbided', 'hand'),
    ('outdo', 'outdid', 'outdoed', 'both'),
    ('outfit', 'outfitted', 'outfited', 'both'),
    ('outgo', 'outwent', 'outgoed', 'both'),
    ('outgrow', 'outgrew', 'outgrowed', 'both'),
    ('output', 'outputted', 'outputed', 'hand'),
    ('outrun', 'outran', 'outruned', 'both'),
    ('outshine', 'outshone', 'outshined', 'both'),
    ('outstrip', 'outstripped', 'outstriped', 'both'),
    ('outwear', 'outwore', 'outweared', 'both'),
    ('outwit', 'outwitted', 'outwited', 'both'),
    ('overbear', 'overbore', 'overbeared', 'both'),
    ('overbid', 'overbid', 'overbided', 'hand'),
    ('overcome', 'overcame', 'overcomed', 'both'),
    ('overcrop', 'overcropped', 'overcroped', 'both'),
    ('overdo', 'overdid', 'overdoed', 'both'),
    ('overdraw', 'overdrew', 'overdrawed', 'both'),
    ('overdrive', 'overdrove', 'overdrived', 'both'),
    ('overeat', 'overate', 'overeated', 'hand'),
    ('overgrow', 'overgrew', 'overgrowed', 'both'),
    ('overhang', 'overhung', 'overhanged', 'both'),
    ('overhear', 'overheard', 'overheared', 'both'),
    ('overlap', 'overlapped', 'overlaped', 'both'),
    ('overlay', 'overlaid', 'overlayed', 'both'),
    ('overlie', 'overlay', 'overlied', 'both'),
    ('overpay', 'overpaid', 'overpayed', 'both'),
    ('override', 'overrode', 'overrided', 'both'),
    ('overrun', 'overran', 'overruned', 'both'),
    ('oversee', 'oversaw', 'overseed', 'both'),
    ('overshoot', 'overshot', 'overshooted', 'hand'),
    ('oversleep', 'overslept', 'oversleeped', 'both'),
    ('overspread', 'overspread', 'overspreaded', 'hand'),
    ('overstep', 'overstepped', 'oversteped', 'both'),
    ('overtake', 'overtook', 'overtaked', 'both'),
    ('overthrow', 'overthrew', 'overthrowed', 'both'),
    ('overwrite', 'overwrote', 'overwrited', 'hand'),
    ('panel', 'panelled', 'paneled', 'both'),
    ('partake', 'partook', 'partaked', 'both'),
    ('patrol', 'patrolled', 'patroled', 'both'),
    ('pay', 'paid', 'payed', 'both'),
    ('pencil', 'pencilled', 'penciled', 'both'),
    ('permit', 'permitted', 'permited', 'both'),
    ('pommel', 'pommelled', 'pommeled', 'both'),
    ('prefer', 'preferred', 'prefered', 'both'),
    ('prepay', 'prepaid', 'prepayed', 'both'),
    ('pretermit', 'pretermitted', 'pretermited', 'both'),
    ('proofread', 'proofread', 'proofreaded', 'hand'),
    ('propel', 'propelled', 'propeled', 'both'),
    ('put', 'put', 'putted', 'unchanging'),
    ('quarrel', 'quarrelled', 'quarreled', 'both'),
    ('quickstep', 'quickstepped', 'quicksteped', 'both'),
    ('quip', 'quipped', 'quiped', 'both'),
    ('quit', 'quit', 'quited', 'hand'),
    ('quiz', 'quizzed', 'quized', 'both'),
    ('rabbet', 'rabbetted', 'rabbeted', 'stress'),
    ('rabbit', 'rabbitted', 'rabbited', 'stress'),
    ('ravel', 'ravelled', 'raveled', 'both'),
    ('read', 'read', 'readed', 'hand'),
    ('readmit', 'readmitted', 'readmited', 'stress'),
    ('reallot', 'reallotted', 'realloted', 'stress'),
    ('rebel', 'rebelled', 'rebeled', 'both'),
    ('rebind', 'rebound', 'rebinded', 'hand'),
    ('rebroadcast', 'rebroadcast', 'rebroadcasted', 'hand'),
    ('rebuild', 'rebuilt', 'rebuilded', 'both'),
    ('rebut', 'rebutted', 'rebuted', 'both'),
    ('recap', 'recapped', 'recaped', 'both'),
    ('recast', 'recast', 'recasted', 'hand'),
    ('recommit', 'recommitted', 'recommited', 'both'),
    ('recur', 'recurred', 'recured', 'both'),
    ('redo', 'redid', 'redoed', 'both'),
    ('refer', 'referred', 'refered', 'both'),
    ('refit', 'refitted', 'refited', 'both'),
    ('regret', 'regretted', 'regreted', 'both'),
    ('rejig', 'rejigged', 'rejiged', 'stress'),
    ('remake', 'remade', 'remaked', 'both'),
    ('remit', 'remitted', 'remited', 'both'),
    ('rend', 'rent', 'rended', 'both'),
    ('repay', 'repaid', 'repayed', 'both'),
    ('repel', 'repelled', 'repeled', 'both'),
    ('reread', 'reread', 'rereaded', 'hand'),
    ('rerun', 'reran', 'reruned', 'both'),
    ('resell', 'resold', 'reselled', 'hand'),
    ('reset', 'reset', 'reseted', 'unchanging'),
    ('reship', 'reshipped', 'reshiped', 'stress'),
    ('resubmit', 'resubmitted', 'resubmited', 'stress'),
    ('retake', 'retook', 'retaked', 'both'),
    ('retell', 'retold', 'retelled', 'both'),
    ('rethink', 'rethought', 'rethinked', 'both'),
    ('retransmit', 'retransmitted', 'retransmited', 'both'),
    ('retrofit', 'retrofitted', 'retrofited', 'both'),
    ('rewrite', 'rewrote', 'rewrited', 'both'),
    ('rid', 'rid', 'ridded', 'hand'),
    ('ride', 'rode', 'rided', 'both'),
    ('ring', 'rang', 'ringed', 'both'),
    ('rise', 'rose', 'rised', 'both'),
    ('run', 'ran', 'runned', 'both'),
    ('sandbag', 'sandbagged', 'sandbaged', 'both'),
    ('say', 'said', 'sayed', 'both'),
    ('see', 'saw', 'seed', 'both'),
    ('seek', 'sought', 'seeked', 'both'),
    ('sell', 'sold', 'selled', 'both'),
    ('send', 'sent', 'sended', 'both'),
    ('set', 'set', 'setted', 'unchanging'),
    ('shake', 'shook', 'shaked', 'both'),
    ('shed', 'shed', 'shedded', 'both'),
    ('shine', 'shone', 'shined', 'both'),
    ('shoot', 'shot', 'shooted', 'both'),
    ('shrink', 'shrank', 'shrinked', 'both'),
    ('shrive', 'shrove', 'shrived', 'both'),
    ('shrivel', 'shrivelled', 'shriveled', 'both'),
    ('shut', 'shut', 'shutted', 'unchanging'),
    ('sidestep', 'sidestepped', 'sidesteped', 'both'),
    ('sing', 'sang', 'singed', 'both'),
    ('sink', 'sank', 'sinked', 'both'),
    ('sit', 'sat', 'sitted', 'both'),
    ('slay', 'slew', 'slayed', 'both'),
    ('sleep', 'slept', 'sleeped', 'both'),
    ('slide', 'slid', 'slided', 'both'),
    ('sling', 'slung', 'slinged', 'both'),
    ('slink', 'slunk', 'slinked', 'both'),
    ('slit', 'slit', 'slitted', 'unchanging'),
    ('smite', 'smote', 'smited', 'both'),
    ('snivel', 'snivelled', 'sniveled', 'both'),
    ('speak', 'spoke', 'speaked', 'both'),
    ('speed', 'sped', 'speeded', 'both'),
    ('spend', 'spent', 'spended', 'both'),
    ('spin', 'spun', 'spinned', 'both'),
    ('spit', 'spat', 'spitted', 'both'),
    ('split', 'split', 'splitted', 'unchanging'),
    ('spread', 'spread', 'spreaded', 'hand'),
    ('spring', 'sprang', 'springed', 'both'),
    ('squat', 'squatted', 'squated', 'both'),
    ('stand', 'stood', 'standed', 'both'),
    ('steal', 'stole', 'stealed', 'both'),
    ('stick', 'stuck', 'sticked', 'both'),
    ('sting', 'stung', 'stinged', 'both'),
    ('stink', 'stank', 'stinked', 'both'),
    ('stride', 'strode', 'strided', 'both'),
    ('strike', 'struck', 'striked', 'both'),
    ('string', 'strung', 'stringed', 'both'),
    ('strive', 'strove', 'strived', 'both'),
    ('sublet', 'subletted', 'subleted', 'stress'),
    ('submit', 'submitted', 'submited', 'both'),
    ('summit', 'summitted', 'summited', 'stress'),
    ('swear', 'swore', 'sweared', 'both'),
    ('sweep', 'swept', 'sweeped', 'both'),
    ('swim', 'swam', 'swimmed', 'both'),
    ('swing', 'swung', 'swinged', 'both'),
    ('take', 'took', 'taked', 'both'),
    ('teach', 'taught', 'teached', 'both'),
    ('tear', 'tore', 'teared', 'both'),
    ('tell', 'told', 'telled', 'both'),
    ('think', 'thought', 'thinked', 'both'),
    ('throw', 'threw', 'throwed', 'both'),
    ('thrust', 'thrust', 'thrusted', 'hand'),
    ('tittup', 'tittupped', 'tittuped', 'both'),
    ('towel', 'towelled', 'toweled', 'both'),
    ('transfer', 'transferred', 'transfered', 'both'),
    ('transmit', 'transmitted', 'transmited', 'both'),
    ('transship', 'transshipped', 'transshiped', 'both'),
    ('tread', 'trod', 'treaded', 'both'),
    ('typecast', 'typecast', 'typecasted', 'hand'),
    ('typeset', 'typeset', 'typeseted', 'unchanging'),
    ('unbar', 'unbarred', 'unbared', 'both'),
    ('unbend', 'unbent', 'unbended', 'both'),
    ('unbind', 'unbound', 'unbinded', 'both'),
    ('unclip', 'unclipped', 'uncliped', 'stress'),
    ('unclog', 'unclogged', 'uncloged', 'both'),
    ('underbid', 'underbid', 'underbided', 'unchanging'),
    ('undercut', 'undercut', 'undercuted', 'unchanging'),
    ('undergo', 'underwent', 'undergoed', 'both'),
    ('underlie', 'underlay', 'underlied', 'both'),
    ('underpay', 'underpaid', 'underpayed', 'both'),
    ('underpin', 'underpinned', 'underpined', 'both'),
    ('undersell', 'undersold', 'underselled', 'both'),
    ('undershoot', 'undershot', 'undershooted', 'both'),
    ('understand', 'understood', 'understanded', 'both'),
    ('undertake', 'undertook', 'undertaked', 'both'),
    ('underwrite', 'underwrote', 'underwrited', 'both'),
    ('undo', 'undid', 'undoed', 'both'),
    ('unfit', 'unfitted', 'unfited', 'both'),
    ('unknot', 'unknotted', 'unknoted', 'stress'),
    ('unman', 'unmanned', 'unmaned', 'both'),
    ('unpin', 'unpinned', 'unpined', 'both'),
    ('unplug', 'unplugged', 'unpluged', 'both'),
    ('unsay', 'unsaid', 'unsayed', 'both'),
    ('unstrap', 'unstrapped', 'unstraped', 'stress'),
    ('unwind', 'unwound', 'unwinded', 'both'),
    ('unwrap', 'unwrapped', 'unwraped', 'both'),
    ('unzip', 'unzipped', 'unziped', 'both'),
    ('up', 'upped', 'uped', 'both'),
    ('uphold', 'upheld', 'upholded', 'both'),
    ('upset', 'upset', 'upseted', 'unchanging'),
    ('victual', 'victualled', 'victualed', 'both'),
    ('wake', 'woke', 'waked', 'both'),
    ('waylay', 'waylaid', 'waylayed', 'both'),
    ('wear', 'wore', 'weared', 'both'),
    ('weatherstrip', 'weatherstripped', 'weatherstriped', 'both'),
    ('weep', 'wept', 'weeped', 'both'),
    ('win', 'won', 'winned', 'both'),
    ('wind', 'wound', 'winded', 'both'),
    ('withdraw', 'withdrew', 'withdrawed', 'both'),
    ('withhold', 'withheld', 'withholded', 'both'),
    ('withstand', 'withstood', 'withstanded', 'both'),
    ('worship', 'worshipped', 'worshiped', 'both'),
    ('wring', 'wrung', 'wringed', 'both'),
    ('write', 'wrote', 'writed', 'both'),
    ('zigzag', 'zigzagged', 'zigzaged', 'both'),
)

PAST_PARTICIPLE = (
    ('abet', 'abetted', 'abeted', 'both'),
    ('abhor', 'abhorred', 'abhored', 'both'),
    ('abut', 'abutted', 'abuted', 'both'),
    ('acquit', 'acquitted', 'acquited', 'both'),
    ('admit', 'admitted', 'admited', 'both'),
    ('allot', 'allotted', 'alloted', 'both'),
    ('annul', 'annulled', 'annuled', 'both'),
    ('apparel', 'apparelled', 'appareled', 'stress'),
    ('arise', 'arisen', 'arised', 'both'),
    ('aver', 'averred', 'avered', 'both'),
    ('awake', 'awoken', 'awaked', 'both'),
    ('baa', 'baaaed', 'baaed', 'stress'),
    ('backbite', 'backbitten', 'backbited', 'both'),
    ('backlog', 'backlogged', 'backloged', 'stress'),
    ('backslap', 'backslapped', 'backslaped', 'stress'),
    ('backslide', 'backslidden', 'backslided', 'both'),
    ('backstop', 'backstopped', 'backstoped', 'stress'),
    ('be', 'been', 'bed', 'both'),
    ('bear', 'born', 'beared', 'both'),
    ('beat', 'beaten', 'beated', 'both'),
    ('bebop', 'bebopped', 'beboped', 'stress'),
    ('become', 'become', 'becomed', 'hand'),
    ('bedim', 'bedimmed', 'bedimed', 'both'),
    ('befall', 'befallen', 'befalled', 'both'),
    ('befit', 'befitted', 'befited', 'both'),
    ('befog', 'befogged', 'befoged', 'both'),
    ('beget', 'begotten', 'begeted', 'both'),
    ('begin', 'begun', 'begined', 'both'),
    ('behold', 'beheld', 'beholded', 'both'),
    ('bend', 'bent', 'bended', 'both'),
    ('beseech', 'besought', 'beseeched', 'both'),
    ('beset', 'beset', 'beseted', 'unchanging'),
    ('bespeak', 'bespoken', 'bespeaked', 'both'),
    ('bestir', 'bestirred', 'bestired', 'both'),
    ('bestride', 'bestridden', 'bestrided', 'both'),
    ('bet', 'bet', 'betted', 'hand'),
    ('bias', 'biassed', 'biased', 'both'),
    ('bid', 'bid', 'bidded', 'hand'),
    ('bind', 'bound', 'binded', 'both'),
    ('bite', 'bitten', 'bited', 'both'),
    ('blackleg', 'blacklegged', 'blackleged', 'both'),
    ('bleed', 'bled', 'bleeded', 'both'),
    ('blow', 'blown', 'blowed', 'both'),
    ('bobsled', 'bobsledded', 'bobsleded', 'stress'),
    ('bootleg', 'bootlegged', 'bootleged', 'both'),
    ('bootstrap', 'bootstrapped', 'bootstraped', 'stress'),
    ('break', 'broken', 'breaked', 'both'),
    ('breed', 'bred', 'breeded', 'both'),
    ('bring', 'brought', 'bringed', 'both'),
    ('broadcast', 'broadcast', 'broadcasted', 'hand'),
    ('browbeat', 'browbeaten', 'browbeated', 'both'),
    ('buckram', 'buckrammed', 'buckramed', 'stress'),
    ('build', 'built', 'builded', 'both'),
    ('burst', 'burst', 'bursted', 'hand'),
    ('bust', 'bust', 'busted', 'hand'),
    ('buy', 'bought', 'buyed', 'both'),
    ('carol', 'carolled', 'caroled', 'both'),
    ('cast', 'cast', 'casted', 'hand'),
    ('catch', 'caught', 'catched', 'both'),
    ('catnap', 'catnapped', 'catnaped', 'both'),
    ('cavil', 'cavilled', 'caviled', 'both'),
    ('channel', 'channelled', 'channeled', 'both'),
    ('choose', 'chosen', 'choosed', 'both'),
    ('cleave', 'cleft', 'cleaved', 'both'),
    ('cling', 'clung', 'clinged', 'both'),
    ('come', 'come', 'comed', 'hand'),
    ('commit', 'committed', 'commited', 'both'),
    ('compel', 'compelled', 'compeled', 'both'),
    ('concur', 'concurred', 'concured', 'both'),
    ('confab', 'confabbed', 'confabed', 'both'),
    ('confer', 'conferred', 'confered', 'both'),
    ('control', 'controlled', 'controled', 'both'),
    ('corral', 'corralled', 'corraled', 'both'),
    ('cost', 'cost', 'costed', 'hand'),
    ('counsel', 'counselled', 'counseled', 'both'),
    ('countersink', 'countersunk', 'countersinked', 'both'),
    ('creep', 'crept', 'creeped', 'both'),
    ('crossbreed', 'crossbred', 'crossbreeded', 'both'),
    ('cudgel', 'cudgelled', 'cudgeled', 'both'),
    ('cut', 'cut', 'cutted', 'unchanging'),
    ('deal', 'dealt', 'dealed', 'both'),
    ('debar', 'debarred', 'debared', 'both'),
    ('debug', 'debugged', 'debuged', 'both'),
    ('defat', 'defatted', 'defated', 'stress'),
    ('defer', 'deferred', 'defered', 'both'),
    ('defog', 'defogged', 'defoged', 'stress'),
    ('demob', 'demobbed', 'demobed', 'both'),
    ('demur', 'demurred', 'demured', 'both'),
    ('deter', 'deterred', 'detered', 'both'),
    ('devil', 'devilled', 'deviled', 'both'),
    ('dial', 'dialled', 'dialed', 'both'),
    ('dig', 'dug', 'digged', 'both'),
    ('disbar', 'disbarred', 'disbared', 'both'),
    ('disbud', 'disbudded', 'disbuded', 'both'),
    ('disembowel', 'disembowelled', 'disemboweled', 'both'),
    ('dishevel', 'dishevelled', 'disheveled', 'both'),
    ('disinter', 'disinterred', 'disintered', 'both'),
    ('dispel', 'dispelled', 'dispeled', 'both'),
    ('distil', 'distilled', 'distiled', 'both'),
    ('do', 'done', 'doed', 'both'),
    ('draw', 'drawn', 'drawed', 'both'),
    ('drink', 'drunk', 'drinked', 'both'),
    ('drive', 'driven', 'drived', 'both'),
    ('duel', 'duelled', 'dueled', 'both'),
    ('dwell', 'dwelt', 'dwelled', 'both'),
    ('eat', 'eaten', 'eated', 'both'),
    ('eavesdrop', 'eavesdropped', 'eavesdroped', 'both'),
    ('embed', 'embedded', 'embeded', 'both'),
    ('emit', 'emitted', 'emited', 'both'),
    ('empanel', 'empanelled', 'empaneled', 'both'),
    ('enamel', 'enamelled', 'enameled', 'both'),
    ('englut', 'englutted', 'engluted', 'both'),
    ('entrap', 'entrapped', 'entraped', 'both'),
    ('enwrap', 'enwrapped', 'enwraped', 'both'),
    ('equal', 'equalled', 'equaled', 'both'),
    ('equip', 'equipped', 'equiped', 'both'),
    ('excel', 'excelled', 'exceled', 'both'),
    ('expel', 'expelled', 'expeled', 'both'),
    ('extol', 'extolled', 'extoled', 'both'),
    ('fall', 'fallen', 'falled', 'both'),
    ('feed', 'fed', 'feeded', 'both'),
    ('feel', 'felt', 'feeled', 'both'),
    ('fight', 'fought', 'fighted', 'both'),
    ('find', 'found', 'finded', 'both'),
    ('flee', 'fled', 'fleed', 'both'),
    ('fling', 'flung', 'flinged', 'both'),
    ('floodlight', 'floodlit', 'floodlighted', 'both'),
    ('fly', 'flown', 'flied', 'both'),
    ('forbear', 'forborne', 'forbeared', 'both'),
    ('forbid', 'forbidden', 'forbided', 'both'),
    ('forecast', 'forecast', 'forecasted', 'hand'),
    ('forego', 'foregone', 'foregoed', 'hand'),
    ('foresee', 'foreseen', 'foreseed', 'both'),
    ('foreswear', 'foresworn', 'foresweared', 'hand'),
    ('foretell', 'foretold', 'foretelled', 'both'),
    ('forget', 'forgotten', 'forgeted', 'both'),
    ('forgive', 'forgiven', 'forgived', 'both'),
    ('forgo', 'forgone', 'forgoed', 'both'),
    ('format', 'formatted', 'formated', 'both'),
    ('forsake', 'forsaken', 'forsaked', 'both'),
    ('forswear', 'forsworn', 'forsweared', 'both'),
    ('freeze', 'frozen', 'freezed', 'both'),
    ('ftp', 'ftpped', 'ftped', 'stress'),
    ('fulfil', 'fulfilled', 'fulfiled', 'both'),
    ('gainsay', 'gainsaid', 'gainsayed', 'both'),
    ('gambol', 'gambolled', 'gamboled', 'both'),
    ('get', 'gotten', 'getted', 'both'),
    ('ghostwrite', 'ghostwritten', 'ghostwrited', 'both'),
    ('gird', 'girt', 'girded', 'both'),
    ('give', 'given', 'gived', 'both'),
    ('go', 'gone', 'goed', 'both'),
    ('grind', 'ground', 'grinded', 'both'),
    ('grovel', 'grovelled', 'groveled', 'both'),
    ('grow', 'grown', 'growed', 'both'),
    ('gyp', 'gypped', 'gyped', 'both'),
    ('hamstring', 'hamstrung', 'hamstringed', 'both'),
    ('handicap', 'handicapped', 'handicaped', 'both'),
    ('hang', 'hung', 'hanged', 'both'),
    ('have', 'had', 'haved', 'both'),
    ('hear', 'heard', 'heared', 'both'),
    ('heave', 'hove', 'heaved', 'both'),
    ('hew', 'hewn', 'hewed', 'both'),
    ('hiccup', 'hiccupped', 'hiccuped', 'both'),
    ('hide', 'hidden', 'hided', 'both'),
    ('hit', 'hit', 'hitted', 'unchanging'),
    ('hold', 'held', 'holded', 'both'),
    ('horsewhip', 'horsewhipped', 'horsewhiped', 'both'),
    ('hurt', 'hurt', 'hurted', 'hand'),
    ('imbed', 'imbedded', 'imbeded', 'both'),
    ('impanel', 'impanelled', 'impaneled', 'hand'),
    ('impel', 'impelled', 'impeled', 'both'),
    ('incur', 'incurred', 'incured', 'both'),
    ('infer', 'inferred', 'infered', 'both'),
    ('initial', 'initialled', 'initialed', 'both'),
    ('inlay', 'inlaid', 'inlayed', 'both'),
    ('input', 'input', 'inputed', 'hand'),
    ('inset', 'inset', 'inseted', 'unchanging'),
    ('inspan', 'inspanned', 'inspaned', 'both'),
    ('instal', 'installed', 'instaled', 'both'),
    ('instil', 'instilled', 'instiled', 'stress'),
    ('inter', 'interred', 'intered', 'both'),
    ('interbreed', 'interbred', 'interbreeded', 'both'),
    ('interweave', 'interwoven', 'interweaved', 'both'),
    ('joyride', 'joyridden', 'joyrided', 'hand'),
    ('keep', 'kept', 'keeped', 'both'),
    ('kennel', 'kennelled', 'kenneled', 'both'),
    ('kidnap', 'kidnapped', 'kidnaped', 'both'),
    ('kneel', 'knelt', 'kneeled', 'both'),
    ('know', 'known', 'knowed', 'both'),
    ('lade', 'laden', 'laded', 'both'),
    ('lay', 'laid', 'layed', 'both'),
    ('lead', 'led', 'leaded', 'both'),
    ('lean', 'leant', 'leaned', 'both'),
    ('leap', 'leapt', 'leaped', 'both'),
    ('leapfrog', 'leapfrogged', 'leapfroged', 'both'),
    ('leave', 'left', 'leaved', 'both'),
    ('lend', 'lent', 'lended', 'both'),
    ('let', 'let', 'letted', 'unchanging'),
    ('libel', 'libelled', 'libeled', 'both'),
    ('lipread', 'lipread', 'lipreaded', 'hand'),
    ('lose', 'lost', 'losed', 'both'),
    ('make', 'made', 'maked', 'both'),
    ('manumit', 'manumitted', 'manumited', 'both'),
    ('marshal', 'marshalled', 'marshaled', 'both'),
    ('marvel', 'marvelled', 'marveled', 'both'),
    ('mean', 'meant', 'meaned', 'both'),
    ('meet', 'met', 'meeted', 'both'),
    ('miscast', 'miscast', 'miscasted', 'hand'),
    ('misdeal', 'misdealt', 'misdealed', 'both'),
    ('misdo', 'misdone', 'misdoed', 'hand'),
    ('mislay', 'mislaid', 'mislayed', 'both'),
    ('mislead', 'misled', 'misleaded', 'both'),
    ('misread', 'misread', 'misreaded', 'hand'),
    ('misspell', 'misspelt', 'misspelled', 'both'),
    ('misspend', 'misspent', 'misspended', 'both'),
    ('mistake', 'mistaken', 'mistaked', 'both'),
    ('misunderstand', 'misunderstood', 'misunderstanded', 'both'),
    ('mow', 'mown', 'mowed', 'both'),
    ('nonplus', 'nonplussed', 'nonplused', 'both'),
    ('occur', 'occurred', 'occured', 'both'),
    ('offset', 'offset', 'offseted', 'unchanging'),
    ('omit', 'omitted', 'omited', 'both'),
    ('outbid', 'outbid', 'outbided', 'hand'),
    ('outdo', 'outdone', 'outdoed', 'both'),
    ('outfit', 'outfitted', 'outfited', 'both'),
    ('outgo', 'outgone', 'outgoed', 'both'),
    ('outgrow', 'outgrown', 'outgrowed', 'both'),
    ('output', 'outputted', 'outputed', 'hand'),
    ('outrun', 'outrun', 'outruned', 'hand'),
    ('outshine', 'outshone', 'outshined', 'both'),
    ('outstrip', 'outstripped', 'outstriped', 'both'),
    ('outwear', 'outworn', 'outweared', 'both'),
    ('outwit', 'outwitted', 'outwited', 'both'),
    ('overbear', 'overborne', 'overbeared', 'both'),
    ('overbid', 'overbidded', 'overbided', 'stress'),
    ('overcome', 'overcome', 'overcomed', 'hand'),
    ('overcrop', 'overcropped', 'overcroped', 'both'),
    ('overdo', 'overdone', 'overdoed', 'both'),
    ('overdraw', 'overdrawn', 'overdrawed', 'both'),
    ('overdrive', 'overdriven', 'overdrived', 'both'),
    ('overeat', 'overeaten', 'overeated', 'hand'),
    ('overgrow', 'overgrown', 'overgrowed', 'both'),
    ('overhang', 'overhung', 'overhanged', 'both'),
    ('overhear', 'overheard', 'overheared', 'both'),
    ('overlap', 'overlapped', 'overlaped', 'both'),
    ('overlay', 'overlaid', 'overlayed', 'both'),
    ('overlie', 'overlain', 'overlied', 'both'),
    ('overpay', 'overpaid', 'overpayed', 'both'),
    ('override', 'overridden', 'overrided', 'both'),
    ('overrun', 'overrun', 'overruned', 'hand'),
    ('oversee', 'overseen', 'overseed', 'both'),
    ('overshoot', 'overshot', 'overshooted', 'both'),
    ('oversleep', 'overslept', 'oversleeped', 'both'),
    ('overspread', 'overspread', 'overspreaded', 'hand'),
    ('overstep', 'overstepped', 'oversteped', 'both'),
    ('overtake', 'overtaken', 'overtaked', 'both'),
    ('overthrow', 'overthrown', 'overthrowed', 'both'),
    ('overwrite', 'overwritten', 'overwrited', 'both'),
    ('partake', 'partaken', 'partaked', 'both'),
    ('patrol', 'patrolled', 'patroled', 'both'),
    ('pay', 'paid', 'payed', 'both'),
    ('pencil', 'pencilled', 'penciled', 'both'),
    ('permit', 'permitted', 'permited', 'both'),
    ('pommel', 'pommelled', 'pommeled', 'both'),
    ('prefer', 'preferred', 'prefered', 'both'),
    ('prepay', 'prepaid', 'prepayed', 'both'),
    ('pretermit', 'pretermitted', 'pretermited', 'both'),
    ('proofread', 'proofread', 'proofreaded', 'hand'),
    ('propel', 'propelled', 'propeled', 'both'),
    ('put', 'put', 'putted', 'unchanging'),
    ('quarrel', 'quarrelled', 'quarreled', 'both'),
    ('quickstep', 'quickstepped', 'quicksteped', 'both'),
    ('quip', 'quipped', 'quiped', 'both'),
    ('quit', 'quitted', 'quited', 'both'),
    ('quiz', 'quizzed', 'quized', 'both'),
    ('rabbet', 'rabbetted', 'rabbeted', 'stress'),
    ('rabbit', 'rabbitted', 'rabbited', 'stress'),
    ('ravel', 'ravelled', 'raveled', 'both'),
    ('read', 'read', 'readed', 'hand'),
    ('readmit', 'readmitted', 'readmited', 'stress'),
    ('reallot', 'reallotted', 'realloted', 'stress'),
    ('rebel', 'rebelled', 'rebeled', 'both'),
    ('rebind', 'rebound', 'rebinded', 'hand'),
    ('rebroadcast', 'rebroadcast', 'rebroadcasted', 'hand'),
    ('rebuild', 'rebuilt', 'rebuilded', 'both'),
    ('rebut', 'rebutted', 'rebuted', 'both'),
    ('recap', 'recapped', 'recaped', 'both'),
    ('recast', 'recast', 'recasted', 'hand'),
    ('recommit', 'recommitted', 'recommited', 'both'),
    ('recur', 'recurred', 'recured', 'both'),
    ('redo', 'redone', 'redoed', 'hand'),
    ('refer', 'referred', 'refered', 'both'),
    ('refit', 'refitted', 'refited', 'both'),
    ('refuel', 'refuelled', 'refueled', 'both'),
    ('regret', 'regretted', 'regreted', 'both'),
    ('rejig', 'rejigged', 'rejiged', 'stress'),
    ('remake', 'remade', 'remaked', 'both'),
    ('remit', 'remitted', 'remited', 'both'),
    ('rend', 'rent', 'rended', 'both'),
    ('repay', 'repaid', 'repayed', 'both'),
    ('repel', 'repelled', 'repeled', 'both'),
    ('reread', 'reread', 'rereaded', 'hand'),
    ('rerun', 'rerun', 'reruned', 'hand'),
    ('resell', 'resold', 'reselled', 'hand'),
    ('reset', 'reset', 'reseted', 'unchanging'),
    ('reship', 'reshipped', 'reshiped', 'stress'),
    ('resubmit', 'resubmitted', 'resubmited', 'stress'),
    ('retake', 'retaken', 'retaked', 'both'),
    ('retell', 'retold', 'retelled', 'both'),
    ('rethink', 'rethought', 'rethinked', 'both'),
    ('retransmit', 'retransmitted', 'retransmited', 'both'),
    ('retrofit', 'retrofitted', 'retrofited', 'both'),
    ('rewrite', 'rewritten', 'rewrited', 'both'),
    ('rid', 'rid', 'ridded', 'hand'),
    ('ride', 'ridden', 'rided', 'both'),
    ('ring', 'rung', 'ringed', 'both'),
    ('rise', 'risen', 'rised', 'both'),
    ('run', 'run', 'runned', 'hand'),
    ('sandbag', 'sandbagged', 'sandbaged', 'both'),
    ('saw', 'sawn', 'sawed', 'both'),
    ('say', 'said', 'sayed', 'both'),
    ('see', 'seen', 'seed', 'both'),
    ('seek', 'sought', 'seeked', 'both'),
    ('sell', 'sold', 'selled', 'both'),
    ('send', 'sent', 'sended', 'both'),
    ('set', 'set', 'setted', 'unchanging'),
    ('sew', 'sewn', 'sewed', 'both'),
    ('shake', 'shaken', 'shaked', 'both'),
    ('shed', 'shed', 'shedded', 'both'),
    ('shine', 'shone', 'shined', 'both'),
    ('shit', 'shat', 'shitted', 'both'),
    ('shoe', 'shod', 'shoed', 'both'),
    ('shoot', 'shot', 'shooted', 'both'),
    ('show', 'shown', 'showed', 'both'),
    ('shrink', 'shrunk', 'shrinked', 'both'),
    ('shrive', 'shriven', 'shrived', 'both'),
    ('shrivel', 'shrivelled', 'shriveled', 'both'),
    ('shut', 'shut', 'shutted', 'unchanging'),
    ('sidestep', 'sidestepped', 'sidesteped', 'both'),
    ('sing', 'sung', 'singed', 'both'),
    ('sink', 'sunk', 'sinked', 'both'),
    ('sit', 'sat', 'sitted', 'both'),
    ('ski', "ski'd", 'skied', 'both'),
    ('slay', 'slain', 'slayed', 'both'),
    ('sleep', 'slept', 'sleeped', 'both'),
    ('slide', 'slid', 'slided', 'both'),
    ('sling', 'slung', 'slinged', 'both'),
    ('slink', 'slunk', 'slinked', 'both'),
    ('slit', 'slit', 'slitted', 'unchanging'),
    ('smell', 'smelt', 'smelled', 'both'),
    ('smite', 'smitten', 'smited', 'both'),
    ('snivel', 'snivelled', 'sniveled', 'both'),
    ('sow', 'sown', 'sowed', 'both'),
    ('speak', 'spoken', 'speaked', 'both'),
    ('speed', 'sped', 'speeded', 'both'),
    ('spell', 'spelt', 'spelled', 'both'),
    ('spend', 'spent', 'spended', 'both'),
    ('spin', 'spun', 'spinned', 'both'),
    ('spit', 'spit', 'spitted', 'hand'),
    ('split', 'split', 'splitted', 'unchanging'),
    ('spoil', 'spoilt', 'spoiled', 'both'),
    ('spread', 'spread', 'spreaded', 'hand'),
    ('spring', 'sprung', 'springed', 'both'),
    ('squat', 'squatted', 'squated', 'both'),
    ('stand', 'stood', 'standed', 'both'),
    ('steal', 'stolen', 'stealed', 'both'),
    ('stick', 'stuck', 'sticked', 'both'),
    ('sting', 'stung', 'stinged', 'both'),
    ('stink', 'stunk', 'stinked', 'both'),
    ('strew', 'strewn', 'strewed', 'both'),
    ('stride', 'stridden', 'strided', 'both'),
    ('strike', 'struck', 'striked', 'both'),
    ('string', 'strung', 'stringed', 'both'),
    ('strive', 'striven', 'strived', 'both'),
    ('sublet', 'subletted', 'subleted', 'stress'),
    ('submit', 'submitted', 'submited', 'both'),
    ('summit', 'summitted', 'summited', 'stress'),
    ('swear', 'sworn', 'sweared', 'both'),
    ('sweep', 'swept', 'sweeped', 'both'),
    ('swim', 'swum', 'swimmed', 'both'),
    ('swing', 'swung', 'swinged', 'both'),
    ('take', 'taken', 'taked', 'both'),
    ('talc', 'talcked', 'talced', 'both'),
    ('teach', 'taught', 'teached', 'both'),
    ('tear', 'torn', 'teared', 'both'),
    ('tell', 'told', 'telled', 'both'),
    ('think', 'thought', 'thinked', 'both'),
    ('throw', 'thrown', 'throwed', 'both'),
    ('thrust', 'thrust', 'thrusted', 'hand'),
    ('tittup', 'tittupped', 'tittuped', 'both'),
    ('towel', 'towelled', 'toweled', 'both'),
    ('transfer', 'transferred', 'transfered', 'both'),
    ('transmit', 'transmitted', 'transmited', 'both'),
    ('transship', 'transshipped', 'transshiped', 'both'),
    ('tread', 'trodden', 'treaded', 'both'),
    ('typecast', 'typecast', 'typecasted', 'hand'),
    ('typeset', 'typeset', 'typeseted', 'unchanging'),
    ('unbar', 'unbarred', 'unbared', 'both'),
    ('unbend', 'unbent', 'unbended', 'both'),
    ('unbind', 'unbound', 'unbinded', 'both'),
    ('unclip', 'unclipped', 'uncliped', 'stress'),
    ('unclog', 'unclogged', 'uncloged', 'both'),
    ('underbid', 'underbid', 'underbided', 'unchanging'),
    ('undercut', 'undercut', 'undercuted', 'unchanging'),
    ('undergo', 'undergone', 'undergoed', 'both'),
    ('underlie', 'underlain', 'underlied', 'both'),
    ('underpay', 'underpaid', 'underpayed', 'both'),
    ('underpin', 'underpinned', 'underpined', 'both'),
    ('undersell', 'undersold', 'underselled', 'both'),
    ('undershoot', 'undershot', 'undershooted', 'both'),
    ('understand', 'understood', 'understanded', 'both'),
    ('undertake', 'undertaken', 'undertaked', 'both'),
    ('underwrite', 'underwritten', 'underwrited', 'both'),
    ('undo', 'undone', 'undoed', 'both'),
    ('unfit', 'unfitted', 'unfited', 'both'),
    ('unknot', 'unknotted', 'unknoted', 'stress'),
    ('unlearn', 'unlearnt', 'unlearned', 'both'),
    ('unman', 'unmanned', 'unmaned', 'both'),
    ('unpin', 'unpinned', 'unpined', 'both'),
    ('unplug', 'unplugged', 'unpluged', 'both'),
    ('unsay', 'unsaid', 'unsayed', 'both'),
    ('unstrap', 'unstrapped', 'unstraped', 'stress'),
    ('unwind', 'unwound', 'unwinded', 'both'),
    ('unwrap', 'unwrapped', 'unwraped', 'both'),
    ('unzip', 'unzipped', 'unziped', 'both'),
    ('up', 'upped', 'uped', 'both'),
    ('uphold', 'upheld', 'upholded', 'both'),
    ('upset', 'upset', 'upseted', 'unchanging'),
    ('victual', 'victualled', 'victualed', 'both'),
    ('waylay', 'waylaid', 'waylayed', 'both'),
    ('wear', 'worn', 'weared', 'both'),
    ('weatherstrip', 'weatherstripped', 'weatherstriped', 'both'),
    ('weave', 'woven', 'weaved', 'both'),
    ('wed', 'wed', 'wedded', 'hand'),
    ('weep', 'wept', 'weeped', 'both'),
    ('wet', 'wet', 'wetted', 'hand'),
    ('win', 'won', 'winned', 'both'),
    ('wind', 'wound', 'winded', 'both'),
    ('withdraw', 'withdrawn', 'withdrawed', 'both'),
    ('withhold', 'withheld', 'withholded', 'both'),
    ('withstand', 'withstood', 'withstanded', 'both'),
    ('worship', 'worshipped', 'worshiped', 'both'),
    ('wring', 'wrung', 'wringed', 'both'),
    ('write', 'written', 'writed', 'both'),
    ('zigzag', 'zigzagged', 'zigzaged', 'both'),
)


#: `db/0022`'s twenty-one, carried forward unchanged: a version is read whole, so a roster that
#: dropped them would silently un-teach the decompiler how to say «is».
def _present_rows():
    from tk2.migrations import discover

    found = next((m for m in discover() if m.number == 22), None)
    if found is None:
        raise RuntimeError("0022 is gone — it holds the present tense this one extends")
    return found.load().PRESENT_TENSE, found.load().NOTES


PRESENT_TENSE, PRESENT_NOTES = _present_rows()

INFLECTION_ROWS = [
    *(
        {
            "version": VERSION,
            "lemma": lemma,
            "tag": TAG_PRESENT,
            "form": form,
            "instead_of": rule_says,
            "source": SOURCE_PRESENT,
            "note": PRESENT_NOTES.get(lemma, ""),
            "position": position,
        }
        for position, (lemma, form, rule_says) in enumerate(PRESENT_TENSE)
    ),
    *(
        {
            "version": VERSION,
            "lemma": lemma,
            "tag": tag,
            "form": form,
            "instead_of": rule_says,
            "source": SOURCE,
            "note": WHY[why],
            "position": position,
        }
        for tag, roster in ((TAG_PAST, PAST_TENSE), (TAG_PARTICIPLE, PAST_PARTICIPLE))
        for position, (lemma, form, rule_says, why) in enumerate(roster)
    ),
]


def _check() -> None:
    from tk2.language.inflect import participle_rule, past_tense_rule, present_tense_rule

    rules = {TAG_PRESENT: present_tense_rule, TAG_PAST: past_tense_rule,
             TAG_PARTICIPLE: participle_rule}
    seen = set()
    for row in INFLECTION_ROWS:
        key = (row["lemma"], row["tag"])
        if key in seen:
            raise ValueError(f"{key} appears twice — one form per lemma per tag")
        seen.add(key)
        if row["form"] == row["instead_of"]:
            raise ValueError(f"{row['lemma']}: the rule already produces {row['form']!r}, so this "
                             f"row is not an exception to anything")
        # **THE ROW MUST DISAGREE WITH THE RULE AS THE CODE STATES IT**, not as this file remembers
        # it. The rule moved four times while this roster was being built, and each time this check
        # named every row the move had invalidated.
        says = rules[row["tag"]](row["lemma"])
        if says != row["instead_of"]:
            raise ValueError(
                f"{row['lemma']} ({row['tag']}): the rule now says {says!r} and this row was "
                f"written against {row['instead_of']!r} — the rule moved under the roster")

    # **NO MODAL.** They are closed-class rows with meanings of their own, and an instrument that
    # answers «could» for `can` is answering a question nobody asked.
    modals = {"can", "will", "shall", "may", "must", "should", "would", "could", "might"}
    intruders = sorted(modals & {row["lemma"] for row in INFLECTION_ROWS})
    if intruders:
        raise ValueError(f"{intruders} are modals and belong in the closed classes, not the roster")


_check()


def up(writer, db) -> None:
    ensure_collections(db, [*ALL_MODELS, *LEDGER_MODELS, *BASE_MODELS])

    writer.insert_many(InflectionDoc, INFLECTION_ROWS)
